#!/bin/sh

exec xautolock -detectsleep \
  -time 3 -locker "i3lock -t -f -e -i '/home/xxx/Images/background.png'" \
  -notify 30 \
  -notifier "notify-send -t 29000 -- 'LOCKING screen in 30 seconds'"
